#!/bin/bash
#
# Oculta uno o mas archivos. Los comodines estan aceptados
#
# Por implementar:
#
#  - Desocultar (mostrar)

USAGE='usage: hide <file> ...'

get_dir ()
{
	if [[ $# -eq 0 ]];then
		echo 'Escriba el nombre de un archivo' >&2
		exit 1
	fi
	(( limite = ${#1}-1 ))

	for (( i=$limite ; i>0 ; i-- ));do
		if [[ "${1:i-1:1}" == "/" ]];then
			echo "${1:0:i}"
			exit 0
		fi
	done

	echo
}

if [ $# -eq 0 ];then
    echo $USAGE
	exit 1
fi

(( OCULTADOS=0 ))

for file in "$@";do
	DIR=`get_dir "$1"`
	FILENAME="${1:${#DIR}}"

    if ! [[ -e $file ]];then
		echo "error: No existe el fichero o directorio «$file»" >&2
    elif [ ${FILENAME:0:1} != "." ];then
		mv "$DIR""$FILENAME" "$DIR"."$FILENAME"
		(( OCULTADOS++ ))
    fi
done 

echo "$OCULTADOS elementos ocultados."
exit 0
