#!/bin/bash
#
# Oculta uno o mas archivos. Los comodines estan aceptados.
#
# Copyright (C) 2015 Ian Mejias
#
# This program is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with 
# this program.  If not, see <http://www.gnu.org/licenses/>.

USAGE='usage: hide FILE...'

get_dir ()
{
	if [[ $# -eq 0 ]];then
		echo 'Escriba el nombre de un archivo' >&2
		exit 1
	fi
	(( limite = ${#1}-1 ))

	for (( i=$limite ; i>0 ; i-- ));do
		if [[ "${1:i-1:1}" == "/" ]];then
			echo "${1:0:i}"
			exit 0
		fi
	done

	echo
}

if [ $# -eq 0 ];then
    echo $USAGE
	exit 1
fi

(( OCULTADOS=0 ))

for file in "$@";do
	DIR=`get_dir "$file"`
	FILENAME="${file:${#DIR}}"

    if ! [[ -e $file ]];then
		echo "error: No existe el fichero o directorio «$file»" >&2
    elif [ ${FILENAME:0:1} != "." ];then
		mv "$DIR""$FILENAME" "$DIR"."$FILENAME"
		(( OCULTADOS++ ))
    fi
done 

echo "$OCULTADOS elementos ocultados."
exit 0
