#!/bin/bash
#
# Crea un nuevo proyecto con algun nombre especificado. Crea la carpeta
# principal y las subcarpetas 'build/obj' y 'src/' en donde se alojaran los
# archivos objeto y fuente respectivamente. Ademas crea el 'Makefile' con las
# variables iniciales: CC, CFLAGS y VPATH que indican el compilador, las
# banderas de compilacion y los directorios de busqueda de dependencias
# respectivamente.
#
# Copyright (C) 2015 Ian Mejias
#
# This program is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with 
# this program.  If not, see <http://www.gnu.org/licenses/>.

make_makefile() {

	if [ -d $1 ] || [ $1 == "" ];then

plantilla="""# Makefile creado automaticamente el $(date +%d/%m/%y) por el script 
# 'new-project':
# https://github.com/Bangaa/Bash-Scripts/blob/master/new-project


# Aqui se deben definir el compilador, la extencion que tiene el codigo fuente 
# y las flags de compilacion (como opciones de optimizacion de codigo, los 
# warnings que desea que se muestren, etc), respectivamente.
CC     =
EXT    =
CFLAGS =

PROGNAME = $1
OBJ =
OBJDIR = obj
VPATH = src/

.PHONY: clean all

all: \$(PROGNAME)

# Se compila el ejecutable
\$(PROGNAME): \$(addprefix \$(OBJDIR)/, \$(OBJ))
	\$(CC) -o \$@ \$^ \$(CFLAGS)

# Se crea el directorio de salida del código objeto
\$(OBJDIR):
	mkdir -p \$@

# Compilación del código objeto
\$(OBJDIR)/%.o: %.\$(EXT) | \$(OBJDIR)
	\$(CC) \$(CFLAGS) -o \$@ -c \$<

# Para empezar de cero
clean:
	rm -f \$(PROGNAME)
	rm -rf \$(OBJDIR)
"""

		echo "$plantilla" > $1/Makefile

		return 0
	else
		echo 'No existe el fichero o directorio' >&2
		return 1
	fi
}

USAGE="uso: new-project [-v] <project name>"

if [ $# -lt 1 ];then
    echo $USAGE
    exit 1
fi

if [[ -d $1 ]];then
    echo "Ya existe un directorio con ese nombre" >&2
    exit 2
fi

if [[ "$1" == "-v" ]];then
    if [[ $# -eq 2 ]];then
		verbose=TRUE
		shift
    else
		echo "Falta el nombre del proyecto" >&2
		exit 2
    fi
else
    verbose=FALSE
fi

OBJ=$1"/build/obj"
SRC=$1"/src"

if [[ $verbose == TRUE ]];then
    flag=-v
else
    flag=""
fi

mkdir -p $flag $OBJ
mkdir -p $flag $SRC

make_makefile $1 && echo "Done" && exit 0


