#!/bin/bash
#
# [es]: Quita los espacios en el nombre de uno o mas archivos, reemplazándolos 
# por guiones bajos.
# [en]: Replace the spaces of one or more files with underscores.
#
# Copyright (C) 2015 Ian Mejias
#
# This program is free software: you can redistribute it and/or modify it under 
# the terms of the GNU General Public License as published by the Free Software 
# Foundation, either version 3 of the License, or (at your option) any later 
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT 
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more 
# details.
#
# You should have received a copy of the GNU General Public License along with 
# this program.  If not, see <http://www.gnu.org/licenses/>.

(( procesados = 0 ))

for archivo in "$@"
do
	nuevo=${archivo//\ /_}

	if  mv "$archivo" $nuevo 2>/dev/null ;then
		(( procesados++ )) 
	else 
		echo "No se hace nada para «$nuevo»."
	fi

done

echo $procesados archivos ahora sin espacios
